library(ggplot2)
rm(list=ls())
options(digits = 4) # by default, print results to four decimal digits
set.seed(1823) #for replication - the year Trinity College was founded!
#replace the empty quotes with the file path to the location where you downloaded the files from Dropbox below
path = "/Users/nicholascrotty/Desktop/Ongoing Trinity Projects/CDVMBG Reviews"

#GENERATE TENSOR OF MATRICES WHERE ROWS, COLUMNS, AND SLICES CORRESPOND TO PREDICTED, ACTUAL, AND OTHER OBJ LOCATION

screenRes = c(2559,1439)
origin = screenRes/2

#----- Load in data -----
#trial-level predictions of distractor position
setwd(paste(path, "/dataForDownload/cnnResults/predictions", sep = ""))
massaPredictions = read.csv("trialLevelPredictions_MassaTargLoc_Decay.csv")
massaPredictions = as.vector(massaPredictions[,-1]) #remove column generated by Excel
grubbLiPredictions = read.csv("trialLevelPredictions_GrubbLiTargLoc_Decay.csv")
grubbLiPredictions = as.vector(grubbLiPredictions[,-1]) #remove column generated by Excel

#conditions files that contain actual distractor position - prior to any preprocessing
setwd(paste(path, "/dataForDownload/oculomotorData", sep = ""))
massaConditionsAll = read.csv("Massa et al. (2024)/CDVMBG_BRM_Massa_Conditions.csv")
massaConditionsAll$subjNum=NULL
grubbLiConditionsAll= read.csv("Grubb & Li (2018)/CDVMBG_BRM_GrubbLi_Conditions.csv")
grubbLiConditionsAll$subjNum=NULL
#read in eye data
massaX_All = read.csv("Massa et al. (2024)/CDVMBG_BRM_Massa_XPos.csv")
massaX_All$X = NULL
massaY_All = read.csv("Massa et al. (2024)/CDVMBG_BRM_Massa_YPos.csv")
massaY_All$X = NULL

grubbLiX_All = read.csv("Grubb & Li (2018)/CDVMBG_BRM_GrubbLi_XPos.csv")
grubbLiX_All$X = NULL
grubbLiY_All = read.csv("Grubb & Li (2018)/CDVMBG_BRM_GrubbLi_YPos.csv")
grubbLiY_All$X = NULL

#Read in behavioral data for RTs
setwd(paste(path, "/dataForDownload/behavioralData", sep = ""))
massaBeh_All = read.csv("CDVMBG_BRM_Massa_Beh.csv")
massaBeh_All$RT = massaBeh_All$RT * 1000

grubbLiRT = read.csv("CDVMBG_BRM_GrubbLi_TargetRT.csv") #already sorted 

#----- Preprocess labels to mirror preprocessing in CNN .ipynb script -----

#perform train-test split on data and labels
massaConditions = data.frame()
grubbLiConditions = data.frame()

massaX = data.frame()
massaY = data.frame()
grubbLiX = data.frame()
grubbLiY = data.frame()

massaBeh = data.frame()
for(t in 1:nrow(massaConditionsAll)){
  conditionsData = massaConditionsAll[t,]
  xData = massaX_All[t,]
  yData = massaY_All[t,]
  behData = massaBeh_All[t,]
  if((t-1) %% 3 == 0){ # we do 't-1' b/c Python starts counts at 0 and R starts counts at 1
    massaConditions = rbind(massaConditions, conditionsData)
    massaX = rbind(massaX, xData)
    massaY = rbind(massaY, yData)
    massaBeh = rbind(massaBeh, behData)
    #BIG THING = rbind(BIG THING, little thing)
    
    
  }
  print(paste0("Massa: ", t))
}

for(t in 1:nrow(grubbLiConditionsAll)){
  conditionsData = grubbLiConditionsAll[t,]
  xData = grubbLiX_All[t,]
  yData = grubbLiY_All[t,]
  if((t-1) %% 3 == 0){ # we do 't-1' b/c Python starts counts at 0 and R starts counts at 1
    grubbLiConditions = rbind(grubbLiConditions, conditionsData)
    grubbLiX = rbind(grubbLiX, xData)
    grubbLiY = rbind(grubbLiY, yData)
    #BIG THING = rbind(BIG THING, little thing)
    
    
  }
  print(paste0("Grubb & Li: ", t))
}
setwd(paste(path, "/dataForDownload/environments", sep = ""))
save(list = ls(.GlobalEnv), file = "CDVMBG_BRM_TargPredictionsAndEyeSorted.RData")

