library(ggplot2)
rm(list=ls())
options(digits = 10) # by default, print results to four decimal digits
set.seed(1823) #for replication - the year Trinity College was founded!
#replace the empty quotes with the file path to the location where you downloaded the files from Dropbox below
path = "/Users/nicholascrotty/Desktop/Ongoing Trinity Projects/CDVMBG Reviews"

screenRes = c(2559,1439)
origin = screenRes/2

#----- Load in data -----
#trial-level predictions of distractor position
setwd(paste(path, "/dataForDownload/cnnResults/predictions", sep = ""))
massaPredictions = read.csv("trialLevelPredictions_MassaDistLoc_Decay.csv")
massaPredictions = as.vector(massaPredictions[,-1]) #remove column generated by Excel
grubbLiPredictions = read.csv("trialLevelPredictions_GrubbLiDistLoc_Decay.csv")
grubbLiPredictions = as.vector(grubbLiPredictions[,-1]) #remove column generated by Excel
doylePredictions = read.csv("trialLevelPredictions_TransferLearning_MassaDistOnDoyleDist_Decay.csv")
doylePredictions = as.vector(doylePredictions[,-1]) #remove column generated by Excel


#conditions files that contain actual distractor position - prior to any preprocessing
setwd(paste(path, "/dataForDownload/oculomotorData", sep = ""))
massaConditionsAll = read.csv("Massa et al. (2024)/CDVMBG_BRM_Massa_Conditions.csv")
massaConditionsAll$subjNum=NULL
grubbLiConditionsAll= read.csv("Grubb & Li (2018)/CDVMBG_BRM_GrubbLi_Conditions.csv")
grubbLiConditionsAll$subjNum=NULL
doyleConditionsAll = read.csv("Doyle et al. (2025)/CDVMBG_Doyle_Conditions.csv")

#read in eye data
massaX_All = read.csv("Massa et al. (2024)/CDVMBG_BRM_Massa_XPos.csv")
massaX_All$X = NULL
massaY_All = read.csv("Massa et al. (2024)/CDVMBG_BRM_Massa_YPos.csv")
massaY_All$X = NULL

grubbLiX_All = read.csv("Grubb & Li (2018)/CDVMBG_BRM_GrubbLi_XPos.csv")
grubbLiX_All$X = NULL
grubbLiY_All = read.csv("Grubb & Li (2018)/CDVMBG_BRM_GrubbLi_YPos.csv")
grubbLiY_All$X = NULL

#read in eye data
doyleX_All = read.csv("Doyle et al. (2025)/CDVMBG_Doyle_XPos.csv")
doyleX_All$X = NULL
doyleY_All = read.csv("Doyle et al. (2025)/CDVMBG_Doyle_YPos.csv")
doyleY_All$X = NULL


setwd(path)
#Read in behavioral data for RTs 
setwd(paste(path, "/dataForDownload/behavioralData", sep = ""))
massaBeh_All = read.csv("CDVMBG_BRM_Massa_Beh.csv")
massaBeh_All$RT = massaBeh_All$RT * 1000

doyleBeh = read.csv("CDVMBG_BRM_Doyle_Beh.csv")
doyleBeh$RT = doyleBeh$RT*1000

grubbLiRT = read.csv("CDVMBG_BRM_GrubbLi_DistractorRT.csv") #already sorted 
grubbLiRT = as.data.frame(grubbLiRT$RT)

#----- Preprocess labels to mirror preprocessing in CNN .ipynb script -----
#remove distractor-absent trials
massaConditionsPresent = massaConditionsAll[!is.na(massaConditionsAll$valueDistractorLocation),]
grubbLiConditionsPresent = grubbLiConditionsAll[!is.na(grubbLiConditionsAll$distractorLocation),]
doyleConditions = doyleConditionsAll[!is.na(doyleConditionsAll$distractorLocation),]

massaX_Present = massaX_All[!is.na(massaConditionsAll$valueDistractorLocation),]
massaY_Present = massaY_All[!is.na(massaConditionsAll$valueDistractorLocation),]
massaBeh_Present = massaBeh_All[!is.na(massaConditionsAll$valueDistractorLocation),]

grubbLiX_Present = grubbLiX_All[!is.na(grubbLiConditionsAll$distractorLocation),]
grubbLiY_Present = grubbLiY_All[!is.na(grubbLiConditionsAll$distractorLocation),]

doyleX = doyleX_All[!is.na(doyleConditionsAll$distractorLocation),]
doyleY = doyleY_All[!is.na(doyleConditionsAll$distractorLocation),]
doyleBeh = doyleBeh[!is.na(doyleConditionsAll$distractorLocation),]

#perform train-test split on labels
massaConditions = data.frame()
grubbLiConditions = data.frame()

massaX = data.frame()
massaY = data.frame()
massaBeh = data.frame()


for(t in 1:nrow(massaConditionsPresent)){
  conditionsData = massaConditionsPresent[t,]
  xData = massaX_Present[t,]
  yData = massaY_Present[t,]
  behData = massaBeh_Present[t,]
  if((t-1) %% 3 == 0){ # we do 't-1' b/c Python starts counts at 0 and R starts counts at 1
    massaConditions = rbind(massaConditions, conditionsData)
    massaX = rbind(massaX, xData)
    massaY = rbind(massaY, yData)
    massaBeh = rbind(massaBeh, behData)
    #BIG THING = rbind(BIG THING, little thing)
    
    
  }
  print(paste0("Massa: ", t))
}


grubbLiX = data.frame()
grubbLiY = data.frame()

for(t in 1:nrow(grubbLiConditionsPresent)){
  conditionsData = grubbLiConditionsPresent[t,]
  xData = grubbLiX_Present[t,]
  yData = grubbLiY_Present[t,]
  if((t-1) %% 3 == 0){ # we do 't-1' b/c Python starts counts at 0 and R starts counts at 1
    grubbLiConditions = rbind(grubbLiConditions, conditionsData)
    grubbLiX = rbind(grubbLiX, xData)
    grubbLiY = rbind(grubbLiY, yData)
    #BIG THING = rbind(BIG THING, little thing)
    
    
  }
  print(paste0("Grubb & Li: ", t))
}


setwd(paste(path, "/dataForDownload/environments", sep = ""))
save(list = ls(.GlobalEnv), file = "CDVMBG_BRM_DistPredictionsAndEyeSorted.RData")

